apiVersion: v1
kind: Service
metadata:
  name: ai-webapp
spec:
  type: ClusterIP
  selector:
    app: ai-webapp
  ports:
    - port: 80
      targetPort: {{ .Values.backend.service.port }}
      protocol: TCP
      name: http
